"""add message edit delete fields

Revision ID: bebb1a956e1a
Revises: '8f1e2d3c4b5a'
Create Date: 2026-08-15 06:22:10.242095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bebb1a956e1a'
down_revision: Union[str, None] = '8f1e2d3c4b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add columns with temporary defaults so existing rows
    # receive valid values.
    op.add_column(
        "messages",
        sa.Column(
            "is_edited",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "messages",
        sa.Column(
            "edited_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.add_column(
        "messages",
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    # Remove server defaults after existing rows have been populated.
    op.alter_column(
        "messages",
        "is_edited",
        server_default=None,
    )

    op.alter_column(
        "messages",
        "is_deleted",
        server_default=None,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_deleted')
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'is_edited')
    # ### end Alembic commands ###
